### ISSUE TITLE
Feature: Possible to also have cv2_waitKey?

### ISSUE THREAD

**Issue by pallgeuer** [modaresimr/opencv_jupyter_ui#1]
When `cv2.imshow` is used in an application, invariably there is usually also a call to `cv2.waitKey`. Do you think there would be any way to support this too remotely somehow?

**Comment by modaresimr** [comment]
Thank you for your interest.
However, i think there is no way to take a key event in Jupiter.
Do you know some ways?

**Comment by pallgeuer** [comment]
I'm no expert, but Jupyter seems to work okay with `input()` reading from stdin, so one of the solutions presented here (https://stackoverflow.com/questions/983354/how-do-i-wait-for-a-pressed-key) for capturing a single character from stdin could potentially work? (using e.g. termios or ncurses?) A crude backup solution would be to use `input()`, which would require an enter after every keypress, but would at least fundamentally allow the code to run at all)

**Comment by modaresimr** [comment]
They are not designed for Jupyter. So they were not working.
I proposed a new idea.
I present a button for waitKey. So by clicking the button, it simulates the key press.

Please install v1.3.2 by `pip install opencv_jupyter_ui==1.3.2`

**Comment by pallgeuer** [comment]
Hey, the button is a cool idea. For many cases that will already be enough!
In my case, my code is going through the frames of a video, and I use different keys to control whether to play/pause and/or step frames. At the moment the button can only send 255 as a return value. Do you think that maybe with the incorporation of some kind of text field or so at least 'normal' characters like a-z, 0-9, space etc could be returned?

**Comment by modaresimr** [comment]
It is imposible in Jupyter to get a single key and textbox is not a good idea too.
I have designed multiple customizable keys. Please upgrade to version 1.4.1
```pip install opencv-jupyter-ui==1.4.1```

**Comment by pallgeuer** [comment]
I can confirm that this works for me and completely covers my use case now. You can close this issue if you agree that this is totally dealt with now. Thanks!
You could also reupdate https://stackoverflow.com/a/71969301/12235376 with the `jcv2.setKeys`.

**Comment by modaresimr** [comment]
Thank you,
I have updated.
Would you please mark the answer as useful (if it is really) in [StackOverflow](https://stackoverflow.com/a/71969301/12235376) to help more people see this project ;)

**Comment by modaresimr** [comment]
in Jupyter it is not possible to get a key
however i think it would be nice to have the possibility to define custom
keys as button
i will add this
